# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1
      MYSQL_DATABASE: test_db
    volumes:
      - ./data/:/var/lib/mysql
    
  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080

  survey:
    build: php
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - 8100:80
    stdin_open: true
    tty: true
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1
      MYSQL_DATABASE: test_db
  
  flaskapp:
    build: flask
    depends_on:
      - db
    volumes:
      - ./flask/:/src/
    ports:
      - 5000:5000
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1
      MYSQL_DATABASE: test_db


